# Generated by Django 4.1.3 on 2022-12-12 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
