# Generated by Django 4.1.3 on 2023-01-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_rating_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
