# Generated by Django 4.1.3 on 2023-01-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_rating_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='suggestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='base.suggestion'),
        ),
    ]
