# Generated by Django 4.1.3 on 2023-01-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rating_review_alter_rating_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='review',
            field=models.FloatField(),
        ),
    ]
