# Generated by Django 4.1.3 on 2023-01-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_suggestion_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userReview',
            field=models.FloatField(default='0'),
        ),
    ]
